### ISSUE TITLE
undefined reference to 'dgepoqrf_

### ISSUE THREAD

**Issue by gudulangzu** [luszczek/paqr#1]
Hello,

When I run paqr_lapack, I encounter an error: "PAQR_work/lapack/test_dgepoqrf.c:146: undefined reference to 'dgepoqrf_'
collect2: error: ld returned 1 exit status."
I also couldn't find the declaration of lapack_dgepoqrf in the included .h header files after the project was compiled. What should I do in this situation? Your guidance would be greatly appreciated.

**Comment by luszczek** [comment]
File `lapack/src/dgepoqrf.f` contains the missing symbol starting at line 145. `lapack_dgepoqrf` is a macro that is commented out on line 9 of `lapack/test_dgepoqrf.c`. The symbol names depend on the Fortran compiler you used so please make the adjustments specific for your build environment.
